language: java

jdk:
  - oraclejdk8

before_install:
  # download play 2.2.4
  - wget http://downloads.typesafe.com/play/2.2.4/play-2.2.4.zip
  - unzip play-2.2.4.zip && rm play-2.2.4.zip && mv play-2.2.4 $HOME/
  - export PLAY_HOME="$HOME/play-2.2.4"
  - echo $PLAY_HOME

  # change the build file stack size
  - sed -i -e 's/-Xss1M/-Xss2M/g' $PLAY_HOME/framework/build
  - cat $PLAY_HOME/framework/build